version: '3.8'

services:
  backend:
    build:
      context: .  # Root directory where requirements.txt is located
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app  # Mounting backend files after installing dependencies
    ports:
      - "8001:8000"  # Change 8000 to 8001 on the host

  frontend:
    build:
      context: ./frontend  # This should point to the frontend directory
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
